variables:
  GIT_SUBMODULE_STRATEGY: recursive

deploy:
  image:
    name: node:alpine
  variables:
    HUGO_ENV: production
  only: [master]
  script:
    - apk add rclone hugo git
    - npm install
    - hugo --gc --minify --enableGitInfo
    - rclone delete --config "$RCLONE_CONFIG" scaleway:blog.flap
    - rclone sync --verbose --config "$RCLONE_CONFIG" ./public  scaleway:blog.flap
