variables:
  GIT_SUBMODULE_STRATEGY: recursive

deploy:
  image: node
  variables:
    HUGO_ENV: production
  only: [master]
  script:
    - apt update
    - apt install -y rclone hugo
    - npm install
    - hugo --gc --minify --enableGitInfo
    - rclone delete --config "$RCLONE_CONFIG" scaleway:blog.flap.cloud
    - rclone sync --verbose --config "$RCLONE_CONFIG" ./public  scaleway:blog.flap.cloud
