image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production

pages:
  only:
    - master
  artifacts:
    paths:
      - public
  script:
    - hugo --minify && gzip -k -6 $(find public -type f)
