baseURL = "https://blog.chmn.me/"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "Blog de FLAP"
theme = "flap-theme"
enableRobotsTXT = true
copyright = "CC-BY-SA - FLAP - 2019-"

[params]
	title = "Blog de FLAP"
	site_logo = "/logo.png"
	description = "FLAP vous aide à comprendre les enjeux qui l'animent."
	images = ["logo_padding.png"]

[menu]
	[[menu.main]]
		identifier = "home"
		name = "Accueil"
		pre = "<img class='px-2' src='https://blog.chmn.me/logo.png' alt='logo' class='w100 mw5-ns' width='70'  height='54'/>"
		url = "https://blog.chmn.me"
		weight = -110
